### PR TITLE
[security issue] IDOR in product quantity

### PR DESCRIPTION
**Pull request by SohaibSEG**
product quatity is explicitely mentioned 
a malcious user could change it to a negative value and buy products for free

### CODE REVIEW

**Comment by dennisivy** [comment]
Good catch, appreciate the changes :)

**Comment by MuhammedNihad** [comment]
This issue isn't updated in the tutorial video, right? @divanov11

**Comment by MuhammedNihad** [comment]
> This issue isn't updated in the tutorial video, right? @divanov11

@divanov11

**Comment by MuhammedNihad** [comment]
> This issue isn't updated in the tutorial video, right? @divanov11

@divanov11 ???

**Pull request merged**
